
- name: debug
  debug:
    msg: "parsing {{ repo_file }}"
    verbosity: 1

- name: load json file
  set_fact:
    file_content: "{{ lookup('file',repo_file)| from_json}}"
  when: repo_file is match(".*json")

- name: load yaml file
  set_fact:
    file_content: "{{ lookup('file',repo_file)| from_yaml}}"
  when: (repo_file is match('.*yml')) or (repo_file is match('.*yaml'))

- name: debug
  debug:
    var: file_content 
    verbosity: 2

- name: image_stream images
  set_fact:
    stream_vars: "{{ file_content|json_query('items[*].spec.tags')|flatten(levels=1)}}"
  when: file_content.kind != "Template"

- name: template images
  set_fact:
    template_vars: "{{ file_content|json_query('objects[*].spec.template.spec.containers[*].image')|flatten(levels=2) }}"
  when: file_content.kind == "Template"

- name: debug
  debug:
    var: "{{ item }}"
    verbosity: 2
  loop:
    #- stream_vars
    - template_vars

- name: collect stream images
  set_fact:
    repo_images: "{{ repo_images| default([]) }} + ['{{item.from.name}}']"
  when: 
    - item.from is defined
    - item.from.kind == "DockerImage"
  loop: "{{ stream_vars|default([]) }}"

- name: collect template images
  set_fact:
    repo_images: "{{ repo_images| default([]) }} + ['{{item}}']"
  when: 
    - item is not match(".*\$.*")
    - item is match(".*/.*")
  loop: "{{ template_vars|default([]) }}"
  



