---
# tasks file for ansible-role-openshift-image

- name: ensure work dir present
  file: 
    path: "{{ work_dir }}"
    state: directory

- name: clone kube repo
  git:
    repo: "{{ image_repo.source }}"
    dest: "{{ work_dir }}/{{image_repo.name}}"
    version: "{{ image_repo.branch }}"
    update: yes

- name: get all image-stream definitions from paths
  find: 
    paths: "{{ work_dir }}/{{image_repo.name}}/{{item}}"
    recurse: yes
    size: '128b'
    patterns: '*.json,*.yml,*.yaml'
  register: _all_files
  loop: "{{ image_repo.paths|default('/') }}"

- name: add all specified files
  set_fact:
    all_files: "{{all_files|default([]) }} + ['{{ work_dir }}/{{image_repo.name}}/{{item}}']"
  loop: "{{ image_repo.files | default([]) }}"

- name: collect specified files
  set_fact: 
    all_files: "{{all_files|default([]) }} + ['{{item.1.path}}']"
  loop: "{{ q( 'subelements', _all_files.results, 'files', {'skip_missing': True}) }}"
  changed_when: False

- name: extract the images
  include_tasks: parse.yml
  loop: "{{ all_files }}"
  loop_control:
    loop_var: repo_file

- name: pretty the list
  set_fact:
    repo_images: "{{ repo_images|sort|unique }}"

- name: debug
  debug:
    var: repo_images
    verbosity: 1

