---
# tasks file for ansible-role-openshift-image

- name: ensure work dir present
  file:
    path: "{{ work_dir }}"
    state: directory

- name: clone kube repo
  git:
    repo: "{{ image_repo.source }}"
    dest: "{{ work_dir }}/{{image_repo.name}}"
    version: "{{ image_repo.branch }}"
    update: yes

- name: get all image-stream definitions from paths
  set_fact:
    #msg: "{{ lookup('file',item.src)| json_query('spec.tags[0]') }}"
    repo_images: "{{(repo_images| default([])) + ((lookup('file',item.src) |from_json).spec.tags | json_query('[?from.kind==`DockerImage`].from.name')|list) }}"
    verbosity: 0
  with_filetree: "{{ work_dir}}/{{image_repo.name}}/{{image_repo.path }}"
  when:
    - item.state == 'file'
    - item.src is regex(".*imagestreams.*.json")
    - item.src is not regex(".*jenkins.*")

- name: asdad
  debug:
    var: repo_images
    verbosity: 1

- name: pretty the list
  set_fact:
    repo_images: "{{ repo_images|sort|unique }}"

- name: debug
  debug:
    var: repo_images
    verbosity: 0

- name: import
  command: "skopeo copy docker://{{ item }} docker://{{mirror_registry}}/{{ item }} --authfile /var/lib/import/auth.json --insecure-policy"
  loop: "{{ repo_images }}"

